# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f93b0bc9dc59133c99779fef6e366deabc3b29dfe7ed5620dd3d415da0dafe49f795a04b33b6f29445c13e70a40ff883441d76d51979e6e943eafb5154c7a0e

test:
  secret_key_base: 59f7e14f08669b0c2a8ec1db9693197f652fea5a21369640304dc8557e6dc3e7843302cdb44f1ff23502918ca7ddf43ea4ff1207ede3b60f9eff64ea403055cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
